test

diff --git a/.github/workflows/ci-deploy-po-version.yml b/.github/workflows/ci-deploy-po-version.yml
--- a/.github/workflows/ci-deploy-po-version.yml
+++ b/.github/workflows/ci-deploy-po-version.yml
@@ -45,7 +45,7 @@ jobs:
               ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' ) ) }}
     runs-on: ubuntu-latest
     steps:
-      - name: Print Contexts/Inputs
+      - name: Print Contexts/Inputs/Variables/Secrets
         shell: bash
         run: |
           echo "[Contexts]"
@@ -58,18 +58,12 @@ jobs:
           echo "inputs.TYPE = ${{ inputs.TYPE }}"
           echo "inputs.VERSION = ${{ inputs.VERSION }}"
           echo "inputs.VERSION_GROUP = ${{ inputs.VERSION_GROUP }}"
-      - name: Check Secrets
-        shell: bash
-        run: |
-          SECRETS_EXIST=true
-          if [[ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]]; then
-            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
-            SECRETS_EXIST=false
-          fi
-          if [[ "${SECRETS_EXIST}" == "false" ]]; then
-            echo "Error: Some secrets are missing." >&2
-            exit 1
-          fi
+          echo "[Variables]"
+          echo "vars.ACTOR_ID = ${{ vars.ACTOR_ID }}"
+          echo "vars.ACTOR_NAME = ${{ vars.ACTOR_NAME }}"
+          echo "vars.ACTOR_LOGIN = ${{ vars.ACTOR_LOGIN }}"
+          echo "[Secrets]"
+          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"
       - name: Check Variables
         shell: bash
         run: |
@@ -88,6 +82,18 @@ jobs:
           fi
           if [[ "${VARIABLES_EXIST}" == "false" ]]; then
             echo "Error: Some variables are missing." >&2
+            exit 1
+          fi
+      - name: Check Secrets
+        shell: bash
+        run: |
+          SECRETS_EXIST=true
+          if [[ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]]; then
+            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [[ "${SECRETS_EXIST}" == "false" ]]; then
+            echo "Error: Some secrets are missing." >&2
             exit 1
           fi
 
