ci: update pr-merged-to-l10n

diff --git a/.github/workflows/ci-pr-merged-to-l10n.yml b/.github/workflows/ci-pr-merged-to-l10n.yml
--- a/.github/workflows/ci-pr-merged-to-l10n.yml
+++ b/.github/workflows/ci-pr-merged-to-l10n.yml
@@ -11,56 +11,47 @@ on:
       - closed
 
 jobs:
-  pr-merged-to-l10n:
-    if: ${{ ( github.event_name == 'pull_request' ) &&
-            ( github.event.pull_request.merged == true ) &&
-            ( contains(github.event.pull_request.labels.*.name, 'gettext') ||
-              contains(github.event.pull_request.labels.*.name, 'crowdin') ) }}
+  precondition:
+    if: ${{ ( ( github.event_name == 'pull_request' ) &&
+              ( github.event.pull_request.merged == 'true' ) &&
+              ( contains(github.event.pull_request.labels.*.name, 'gettext') ||
+                contains(github.event.pull_request.labels.*.name, 'crowdin') ) ) }}
     runs-on: ubuntu-latest
     steps:
-      - name: Print Contexts/Inputs/Secrets
+      - name: Check Secrets
         shell: bash
         run: |
-          echo "[Contexts]"
-          echo "github.job = ${{ github.job }}"
-          echo "github.ref = ${{ github.ref }}"
-          echo "github.ref_name = ${{ github.ref_name }}"
-          echo "github.event.action = ${{ github.event.action }}"
-          echo "github.event.number = ${{ github.event.number }}"
-          echo "github.event_name = ${{ github.event_name }}"
-          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
-          echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
-          echo "github.base_ref = ${{ github.base_ref }}"
-          echo "github.head_ref = ${{ github.head_ref }}"
-          echo "[Inputs]"
-          echo "[Secrets]"
-          echo "secrets.APP_ID = ${{ secrets.APP_ID }}"
-          echo "secrets.APP_PRIVATE_KEY = ${{ secrets.APP_PRIVATE_KEY }}"
-
-      - name: Extract VERSION from the Pull Request Title
-        id: evprt
+          SECRETS_EXIST=true
+          if [[ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]]; then
+            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [[ "${SECRETS_EXIST}" == "false" ]]; then
+            echo "Error: Some secrets are missing." >&2
+            exit 1
+          fi
+      - name: Check Variables
+        shell: bash
         run: |
-          PR_TITLE="${{ github.event.pull_request.title }}"
-          VERSION_REGEX="pot\(([^)]+)\):"
-          if [[ $PR_TITLE =~ $VERSION_REGEX ]]; then
-            VERSION="${BASH_REMATCH[1]}"
-            echo "Extracted version: $VERSION"
-            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
-          else
-            echo "Version format not found in PR title"
+          VARIABLES_EXIST=true
+          if [[ "${VARIABLES_EXIST}" == "false" ]]; then
+            echo "Error: Some variables are missing." >&2
             exit 1
           fi
 
-      - name: Dispatch the 'pr-merged-to-l10n' event to the repository
-        uses: peter-evans/repository-dispatch@v3
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          event-type: pr-merged-to-l10n
-          client-payload: |
-            {
-              "TYPE" : "single",
-              "VERSION" : "${{ steps.evprt.outputs.VERSION }}",
-              "LANGUAGE" : "all",
-              "GETTEXT" : "${{ contains(github.event.pull_request.labels.*.name, 'gettext') }}",
-              "CROWDIN" : "${{ contains(github.event.pull_request.labels.*.name, 'crowdin') }}"
-            }
+  caller:
+    needs: [ 'precondition' ]
+    if: ${{ ( ( github.event_name == 'pull_request' ) &&
+              ( github.event.pull_request.merged == 'true' ) &&
+              ( contains(github.event.pull_request.labels.*.name, 'gettext') ||
+                contains(github.event.pull_request.labels.*.name, 'crowdin') ) ) }}
+    uses: hwhsu1231/ci-sphinx/.github/workflows/use-pr-merged-to-l10n.yml@main
+    with:
+      RUNNER: 'ubuntu-latest'
+      PR_TITLE: ${{ github.event.pull_request.title }}
+      GETTEXT: ${{ contains(github.event.pull_request.labels.*.name, 'gettext') }}
+      TMSCLI: ${{ contains(github.event.pull_request.labels.*.name, 'tmscli') }}
+      CALLER_JOB: 'caller'
+      ENABLE_JOB: true
+    secrets:
+      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
