ci: add some error messages

diff --git a/.github/workflows/ci-tmscli-pull-po.yml b/.github/workflows/ci-tmscli-pull-po.yml
--- a/.github/workflows/ci-tmscli-pull-po.yml
+++ b/.github/workflows/ci-tmscli-pull-po.yml
@@ -72,6 +72,7 @@ jobs:
             SECRETS_EXIST=false
           fi
           if [[ "${SECRETS_EXIST}" == "false" ]]; then
+            echo "Error: Some secrets are missing." >&2
             exit 1
           fi
       - name: Check Variables
@@ -91,6 +92,7 @@ jobs:
             VARIABLES_EXIST=false
           fi
           if [[ "${VARIABLES_EXIST}" == "false" ]]; then
+            echo "Error: Some variables are missing." >&2
             exit 1
           fi
 
diff --git a/.github/workflows/ci-tmscli-readme.yml b/.github/workflows/ci-tmscli-readme.yml
--- a/.github/workflows/ci-tmscli-readme.yml
+++ b/.github/workflows/ci-tmscli-readme.yml
@@ -45,6 +45,7 @@ jobs:
             SECRETS_EXIST=false
           fi
           if [[ "${SECRETS_EXIST}" == "false" ]]; then
+            echo "Error: Some secrets are missing." >&2
             exit 1
           fi
       - name: Check Variables
@@ -64,6 +65,7 @@ jobs:
             VARIABLES_EXIST=false
           fi
           if [[ "${VARIABLES_EXIST}" == "false" ]]; then
+            echo "Error: Some variables are missing." >&2
             exit 1
           fi
 
