test

diff --git a/.github/workflows/ci-tmscli-push-pot.yml b/.github/workflows/ci-tmscli-push-pot.yml
--- a/.github/workflows/ci-tmscli-push-pot.yml
+++ b/.github/workflows/ci-tmscli-push-pot.yml
@@ -43,18 +43,6 @@ jobs:
               ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' ) ) }}
     runs-on: ubuntu-latest
     steps:
-      - name: Check Secrets
-        shell: bash
-        run: |
-          SECRETS_EXIST=true
-          if [[ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]]; then
-            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
-            SECRETS_EXIST=false
-          fi
-          if [[ "${SECRETS_EXIST}" == "false" ]]; then
-            echo "Error: Some secrets are missing." >&2
-            exit 1
-          fi
       - name: Check Variables
         shell: bash
         run: |
@@ -75,6 +63,18 @@ jobs:
             echo "Error: Some variables are missing." >&2
             exit 1
           fi
+      - name: Check Secrets
+        shell: bash
+        run: |
+          SECRETS_EXIST=true
+          if [[ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]]; then
+            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [[ "${SECRETS_EXIST}" == "false" ]]; then
+            echo "Error: Some secrets are missing." >&2
+            exit 1
+          fi
       - name: Print Contexts/Inputs
         shell: bash
         run: |
@@ -92,6 +92,12 @@ jobs:
           echo "inputs.TYPE = ${{ inputs.TYPE }}"
           echo "inputs.VERSION = ${{ inputs.VERSION }}"
           echo "inputs.VERSION_GROUP = ${{ inputs.VERSION_GROUP }}"
+          echo "[Variables]"
+          echo "vars.ACTOR_ID = ${{ vars.ACTOR_ID }}"
+          echo "vars.ACTOR_NAME = ${{ vars.ACTOR_NAME }}"
+          echo "vars.ACTOR_LOGIN = ${{ vars.ACTOR_LOGIN }}"
+          echo "[Secrets]"
+          echo "secrets.CROWDIN_PERSONAL_TOKEN = ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"
 
   get-matrix:
     needs: [ 'precondition' ]
diff --git a/.github/workflows/ci-tmscli-readme.yml b/.github/workflows/ci-tmscli-readme.yml
--- a/.github/workflows/ci-tmscli-readme.yml
+++ b/.github/workflows/ci-tmscli-readme.yml
@@ -29,22 +29,6 @@ jobs:
             ( github.event_name == 'workflow_dispatch' ) }}
     runs-on: ubuntu-latest
     steps:
-      - name: Check Secrets
-        shell: bash
-        run: |
-          SECRETS_EXIST=true
-          if [[ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]]; then
-            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
-            SECRETS_EXIST=false
-          fi
-          if [[ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]]; then
-            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
-            SECRETS_EXIST=false
-          fi
-          if [[ "${SECRETS_EXIST}" == "false" ]]; then
-            echo "Error: Some secrets are missing." >&2
-            exit 1
-          fi
       - name: Check Variables
         shell: bash
         run: |
@@ -65,6 +49,40 @@ jobs:
             echo "Error: Some variables are missing." >&2
             exit 1
           fi
+      - name: Check Secrets
+        shell: bash
+        run: |
+          SECRETS_EXIST=true
+          if [[ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]]; then
+            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [[ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]]; then
+            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [[ "${SECRETS_EXIST}" == "false" ]]; then
+            echo "Error: Some secrets are missing." >&2
+            exit 1
+          fi
+      - name: Print Contexts/Inputs/Variables/Secrets
+        shell: bash
+        run: |
+          echo "[Contexts]"
+          echo "github.job = ${{ github.job }}"
+          echo "github.ref = ${{ github.ref }}"
+          echo "github.ref_name = ${{ github.ref_name }}"
+          echo "github.event_name = ${{ github.event_name }}"
+          echo "github.event.schedule = ${{ github.event.schedule }}"
+          echo "[Inputs]"
+          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
+          echo "[Variables]"
+          echo "vars.ACTOR_ID = ${{ vars.ACTOR_ID }}"
+          echo "vars.ACTOR_NAME = ${{ vars.ACTOR_NAME }}"
+          echo "vars.ACTOR_LOGIN = ${{ vars.ACTOR_LOGIN }}"
+          echo "[Secrets]"
+          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"
+          echo "secrets.CROWDIN_PERSONAL_TOKEN = ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"
 
   caller:
     needs: [ 'precondition' ]
